apiVersion: apps/v1
kind: Deployment
metadata:
  name: fifth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fifth
  template:
    metadata:
      labels:
        app: fifth
    spec:
      containers:
      - name: fifth
        image: yklee2002/fifth:latest
        ports:
        - containerPort: 8093
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/bookdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "rootpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: fifth-service
spec:
  selector:
    app: fifth
  ports:
  - protocol: TCP
    port: 8093
    targetPort: 8093
  type: NodePort
