server:  
  port: ${PORT:8889}
    
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leeyoungkon/spring-cloud-config-repo.git
          username: leeyoungkon
          password: byby3845//
          cloneOnStart: true
          force-pull: true
          default-label: main
     