server:  
  port: ${PORT:8080}

spring:  
  application:
    name: gateway-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    
zuul:
  prefix: /api
  routes:
    account-service:
      path: /account/**
    customer-service:
      path: /customer/**
    order-service:
      path: /order/**
    product-service:
      path: /product/**

management:
  security:
    enabled: false