node('dind-node-1') {
 withMaven(maven:'M3') {
  stage('Checkout') {
   git url: 'https://github.com/leeyoungkon/springcloud.git', credentialsId: 'leeyoungkon',   branch: 'docker'
  }

  stage('Build') {
   dir('order-service') {
    sh 'mvn clean install -Dmaven.test.skip=true'
   }
   def pom = readMavenPom file:'pom.xml'
   print pom.version
   env.version = pom.version
   currentBuild.description = "Release: ${env.version}"
  }

  stage('Image') {
   dir ('order-service') {
    def app = docker.build "yklee2002/order-service:${env.version}"
    //app.push()
   }
  }

  stage ('Run') {
   docker.image("yklee2002/order-service:${env.version}").run('-p 8090:8090 -m 256M -e EUREKA_DEFAULT_ZONE=http://discovery:8761/eureka -d --name order --network sample-spring-cloud-network')
  }

 }
}
