spring:  
  application:
    name: client-service

server:  
  port: ${PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
   
endpoints:
  shutdown:
    enabled: true
    sensitive: false