spring:
  profiles: peer1
 
  application:
    name: discovery-service

server:  
  port: ${PORT:8761}
      
eureka:
  instance:
    hostname: peer1
    metadataMap: 
      zone: zone1
  client:
    serviceUrl: 
      defaulrZone:
        http://localhost:8762/eureka/, http://localhost:8763/eureka/
---
spring:
  profiles: peer2
 
  application:
    name: discovery-service

server:  
  port: ${PORT:8762}
      
eureka:
  instance:
    hostname: peer2
    metadataMap: 
      zone: zone2
  client:
    serviceUrl: 
      defaulrZone:
        http://localhost:8761/eureka/, http://localhost:8763/eureka/
---
spring:
  profiles: peer3
 
  application:
    name: discovery-service

server:  
  port: ${PORT:8763}
      
eureka:
  instance:
    hostname: peer3
    metadataMap: 
      zone: zone3
  client:
    serviceUrl: 
      defaulrZone:
        http://localhost:8761/eureka/, http://localhost:8762/eureka/


        
