apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave
    spec:
      containers:
      - name: slave
        image: yklee2002/slave:latest
        ports:
        - containerPort: 8100
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/bookdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "rootpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: slave-service
spec:
  selector:
    app: slave
  ports:
  - protocol: TCP
    port: 8100
    targetPort: 8100
  type: NodePort
