server:
  port: 8092
  
account-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: account-service:8091, account-service:9091
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

    
logging:
  level:
   com.netflix: DEBUG
   org.springframework.cloud: DEBUG