node('dind-node-1') {
 withMaven(maven:'M3') {
  stage('Checkout') {
   git url: 'https://github.com/leeyoungkon/springcloud.git', credentialsId: 'leeyoungkon',   branch: 'docker'
  }

  stage('Build') {
   dir('discovery-service') {
    sh 'mvn clean install'
   }
   def pom = readMavenPom file:'pom.xml'
   print pom.version
   env.version = pom.version
   currentBuild.description = "Release: ${env.version}"
  }

  stage('Image') {
   dir ('discovery-service') {
    def app = docker.build "yklee2002/discovery-service:${env.version}"
    //app.push()
   }
  }

  stage ('Run') {
   docker.image("yklee2002/discovery-service:${env.version}").run('-p 8761:8761 -m 256M -d --name discovery --network sample-spring-cloud-network')
  }

 }
}