server:  
  port: ${PORT:8080}

spring:  
  application:
    name: gateway-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    
zuul:
  prefix: /api
  routes:
    order-service:
      path: /order/**

management:
  security:
    enabled: false